### ISSUE TITLE
can't install this iso, please help me

### ISSUE THREAD

**Issue by ipang-dwi** [adi1090x/CustomArch#11]
hi, nice to try your customArch os.. I was trying it on live usb, but when I gonna to install, I get a trouble like this https://ibb.co/2jqC8Gs.. can you help me, how to fix it.. not just in openbox session, but also in lxde session too.. thanks for your attention..

**Comment by adi1090x** [comment]
looks like an I/O error. reboot and try again.

**Comment by ipang-dwi** [comment]
i was trying it again, about 3 times, and still give me error like that.. is there any method to install it manually??

**Comment by anark1stx** [comment]
> i was trying it again, about 3 times, and still give me error like that.. is there any method to install it manually??

You can perform a classical archiso installation through the terminal, make sure you use a root acc.

**Comment by adi1090x** [comment]
to install it manually, you need to 
+ boot the live iso
+ setup the partition
+ extract the filesystem to target partition
+ copy the kernel from live iso to boot dir in the root fs
+ chroot into the fs and rebuilt initrd
+ install grub and update the conf
+ reboot.
