### ISSUE TITLE
Theme configuration files

### ISSUE THREAD

**Issue by Tchoupinax** [adi1090x/CustomArch#12]
Hello,

I find your project awesome, thanks !
I am looking for configuration files (i3, polybar). I saw that `setup.sh` clones repos but i do not see nothing about configuration files copy. Where are there ? :)

**Comment by anark1stx** [comment]
Read the original post, the link is attached.
https://www.reddit.com/r/unixporn/comments/gglodg/oc_archiso_second_version_of_my_custom_arch_linux/

https://github.com/adi1090x/CustomArch/tree/version-2.0/iso/airootfs/etc/skel
