### ISSUE TITLE
Restart infinite loop

### ISSUE THREAD

**Issue by anark1stx** [adi1090x/CustomArch#13]
It's been 4 hours since I installed it.
I wanted to reboot to check if Windows 10 was still bootable.

But when I click restart (Windows key + x > Restart) I get that loading gif of colours. I left it for 7 minutes now and it's still going.

**Comment by adi1090x** [comment]
there must be a non responding service or something, you still face this issue?

**Comment by anark1stx** [comment]
Hello, yes I do. Instead of rebooting I'm just shuting down.
Journal logs don't say anything about a proccess running so idk.
