### ISSUE TITLE
CustomArch with blackbox

### ISSUE THREAD

**Issue by drmarwat** [adi1090x/CustomArch#14]
Hello,
Could you make CustomArch ISO with blackbox WM only please with your own settings ?

**Comment by adi1090x** [comment]
But why? According to Arch wiki

> Blackbox was last updated November 3, 2005 with no plans for future releases.

I know there is a github version available but it's not worth it.

I've used blackbox a while ago, if you want the configurations... [Here](https://github.com/adi1090x/dots#3-bbox)

**Comment by drmarwat** [comment]
I just still like blackbox , I know its dead and personally I liked how you made your blackbox ISO here https://www.reddit.com/r/unixporn/comments/adldeh/blackbox_just_getting_my_hands_on_blackbox_wm/
So If you could just recreate the same in a small ISO for me with just basics and these settings.
thanks,

**Comment by adi1090x** [comment]
I'm sorry. I am too busy to create ISOs for individuals.
If you like that config of blackbox, then use those dotfiles and set it up for you.
