### ISSUE TITLE
Can't find a way to install V2.0

### ISSUE THREAD

**Issue by garret** [adi1090x/CustomArch#17]
From your installation guide I can see that it should be possible to easily install this system by clicking on the "Install it" menu entry in Openbox. However, I cannot find it in version 2.0. 

At the moment, I am booting the 2.0 live on virtualbox but just because I wanted to try it. My plan was to simulate an installation on the virtualmachine HDD. 

In any case, I tried to start the installer by giving `/abif-master/abif` and I get an error that I need to be root. Thus, I opened a root terminal (via your openbox menu) and gave the same command. However, now I get a permission denied continuous error, so not allowing myself to do any operation. 

Do you know how to install this new version from OpenBox or bspwm?

**Comment by adi1090x** [comment]
In V2.0, it's `Install Archlinux`.
And I'm currently trying both options you mentioned here, it's working just fine, not sure what wrong you did.

**Comment by adi1090x** [comment]
Press the super/meta/windows key, or just alt+F1, it'll open the Rofi app launcher. Type install and run it.
Or go to application>system in openbox menu.

**Comment by garret** [comment]
Ok but then I get this continuing error of "permission denied". I have put "liveuser" as root password.

**Comment by adi1090x** [comment]
You've tried any other VM?

**Comment by pucilpet** [comment]
I have the same issue. When I click "install", it asks for a sudo password. I tried to use liveuser but nothing happens after that. Maybe the sudo password is something else?

**Comment by garret** [comment]
I only tried on latest version of Vritualbox where I have already installed arch or other distributions. I also downloaded the .iso from the mega.nz link.

**Comment by garret** [comment]
By doing in this way
