### ISSUE TITLE
Couldn't successfully build ISO using ur readme Intructions.

### ISSUE THREAD

**Issue by Shabinder** [adi1090x/CustomArch#18]
after setup.sh command i do sudo su and then ./build.sh -v,
following is the output -

# ./build.sh -v

[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   init
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:        Pacman config file:   work/pacman.conf

[mkarchiso] INFO: Installing packages to 'work/x86_64/airootfs/'...
==> Creating install root at work/x86_64/airootfs
==> Installing packages to work/x86_64/airootfs
error: could not register 'localrepo' database (database already registered)
error: could not register 'localrepo' database (database already registered)
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
error: failed retrieving file 'localrepo.db' from disk : Couldn't open file /home/shabinder/archlinux/localrepo/x86_64/localrepo.db
error: failed to update localrepo (download library error)
error: failed to synchronize all databases
==> ERROR: Failed to install packages to new root

**Comment by Shabinder** [comment]
i removed duplicate local repo entries from work/pacman.conf , 
but still upon building , i encounter this error-

error: failed retrieving file 'localrepo.db' from disk : Couldn't open file /home/shabinder/archlinux/localrepo/x86_64/localrepo.db
error: failed to update localrepo (download library error)
error: failed to synchronize all databases

**Comment by adi1090x** [comment]
Check the localrepo dir and see if the db file exist.

**Comment by adi1090x** [comment]
Also, you should completely remove the work dir before rebuilding the ISO.

**Comment by Shabinder** [comment]
there isnt any

**Comment by adi1090x** [comment]
The error above shows that local repo failed to setup correctly.

**Comment by Shabinder** [comment]
local db is empty , so how to create aone

**Comment by Shabinder** [comment]
I will try to clean all the mess i might have created and start new

**Comment by adi1090x** [comment]
Use the repo-add command inside the package dir, just open the setup.sh, and copy paste the repo-add command.

**Comment by adi1090x** [comment]
Also, which version you're trying to build?

**Comment by Shabinder** [comment]
version 1

**Comment by Shabinder** [comment]
and one more thing ....
[*] Building rxvt-unicode-pixbuf - 
==> Making package: rxvt-unicode-pixbuf 9.22-2 (Thu May 28 20:25:42 2020)
==> Checking runtime dependencies...
error: could not register 'local' database (database already registered)
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading rxvt-unicode-9.22.tar.bz2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (28) Failed to connect to dist.schmorp.de port 80: Connection timed out
Warning: Transient problem: timeout Will retry in 3 seconds. 3 retries left.


i have a very good internet connection , only this fails,else all downloads and builds successfully..

**Comment by adi1090x** [comment]
That's why, it's because i3lock-fancier is not compiling correct, i will update it with another lockscreen program soon, i was busy with v2.0.

You need to setup the localrepo manually, also you need to remove the i3lock-fancier from package file.

**Comment by Shabinder** [comment]
ohk Sure, i will wait...
