### ISSUE TITLE
Sudo credentials for the live ISO?

### ISSUE THREAD

**Issue by sakshatshinde** [adi1090x/CustomArch#20]
I messed up an X11 conf file and now I am not able to  boot into my install. I was thinking maybe I can just undo the change using the live ISO. But for that I would require SU perms.

**Comment by adi1090x** [comment]
**liveuser** is the sudo password in live ISO.

**Comment by sakshatshinde** [comment]
Hmm that's weird since it didn't work for me, I tried that one multiple times and gave up and downloaded vanilla arch iso to use and fix the issue.

**Comment by sakshatshinde** [comment]
For now I'm closing this issue.
