### ISSUE TITLE
Trademark infringement

### ISSUE THREAD

**Issue by Foxboron** [adi1090x/CustomArch#8]
Yo!

If you read over the trademark policy of "Arch Linux" you'll notice that this project can't be called Arch, nor give the impression that it is Arch Linux.

https://wiki.archlinux.org/index.php/DeveloperWiki:TrademarkPolicy

Please consider finding another suitable name for your distribution.

**Comment by brneor** [comment]
Doesn't this project fit under

> "what you are referring to is in fact Arch Linux. If someone is confused into thinking that what isn't Arch Linux is in fact Arch Linux, you are probably doing something wrong."

of "Permitted Use" section?

**Comment by Foxboron** [comment]
Indeed. Reading the next section is also important.

>the Trademark is used in a way that makes it clear that your project is a development effort related to the Arch Linux source, but that the software you are working upon is not in fact Arch Linux as distributed by the Arch Linux project

**Comment by adi1090x** [comment]
Thanks for letting me know, but...

> An Arch Linux Based Custom ISO Made With Archiso, Specially for newbies and DIY enthusiasts. 

> Acceptable project titles would be "System Management for Arch Linux" or "Arch Linux Based Systems Management".

I guess, my project is pretty straightforward. It's non commercial, free for anyone who is interested. And i guess people who came to this project, also aware of what is **ArchLinux** Already.

**Comment by Foxboron** [comment]
The project is still called "archlinux" and I as it currently stand, a derivative distribution.

**Comment by adi1090x** [comment]
Yes, But... I can't change the repository name. But I'll change the distribution name, ISO label... Maybe like "remix" or something... Hope that'll be okay for all that trademark ans stuff.

**Comment by Foxboron** [comment]
You can change the repository name. Github automatically redirects the URLs for a year.

**Comment by Thomashighbaugh** [comment]
Not trying to beat a dead horse, you really should change the repository name before someone kicks this into court to make an example out of you/this project or your name is somehow tarnished because a lawyer smells blood in the water. You work too hard to fall that way friend.

**Comment by adi1090x** [comment]
Yes, I'm going to do it, i was a bit busy... Any suggestions for name, @thomashighbaugh @foxboron

**Comment by adi1090x** [comment]
How about **customarch** ???

**Comment by Thomashighbaugh** [comment]
Yeah its kind of perfect actually. You could style it like Custom-Arch or CustomArch and call it CA Linux for short even. I like it but I am easy to please!

**Comment by adi1090x** [comment]
So, I've changed the name of repository to **CustomArch**.
Also I've mentioned this - 

> This project is just a derivative of Arch Linux, It's Not Arch Linux itself.

is there anything else i need to do, @Foxboron ?

**Comment by Foxboron** [comment]
Looks fine :) Thanks!

**Comment by adi1090x** [comment]
okay, great. closing it.
